-- ============================================================
-- Archivo: 04_insertar_validar_xml.sql
-- Descripción: Inserción y validación de XML en Oracle
-- ============================================================

CREATE TABLE hr_xml_data (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    documento XMLTYPE
);

INSERT INTO hr_xml_data (documento)
VALUES (
    XMLTYPE(
        BFILENAME('XMLDIR', 'BaseDatosHR.xml'),
        NLS_CHARSET_ID('AL32UTF8')
    )
);

COMMIT;

SELECT id,
       documento.ISSCHEMAVALID('BaseDatosHR.xsd') AS es_valido
FROM hr_xml_data;